//
//  SongRepositoryTests.swift
//  gk-iosTests
//
//  Exercises `SongRepository` against the real bundled corpus (703 songs + manifest.json +
//  song_groups.json, all copied verbatim from pipeline/converted). Hosted unit test target, so
//  `SongRepository.shared` (backed by `Bundle.main`) resolves the same bundle the app ships —
//  see `SongCodableDecodingTests` for why. Facts asserted below (uids, md5, counts) were verified
//  directly against the source JSON, not guessed.

import XCTest
@testable import gk_ios

final class SongRepositoryTests: XCTestCase {

    private var repository: SongRepository { .shared }

    // MARK: - Manifest load (docs/data/manifest.md)

    /// Non-song JSON that ships at the same (flattened) bundle level as the corpus, and so must be
    /// excluded when deriving "one ManifestEntry per bundled song file".
    private static let nonSongResources: Set<String> = [
        "manifest", "calendar", "song_groups", "gg_hierarchy"
    ]

    func testManifestLoadsAllSongsWithUniqueUids() throws {
        let manifest = repository.manifest
        XCTAssertEqual(Set(manifest.map(\.uid)).count, manifest.count, "uid must be unique per manifest.md")

        // manifest.md: one ManifestEntry per bundled song file. Derived from what is actually in the
        // bundle rather than pinned to a literal — the corpus is regenerated by the pipeline, and a
        // hardcoded total goes stale the first time a song is added or removed (this assertion used
        // to read `703` while the bundle shipped 702).
        let bundled = try XCTUnwrap(Bundle.main.urls(forResourcesWithExtension: "json", subdirectory: nil))
        let songFileUids = Set(
            bundled.map { $0.deletingPathExtension().lastPathComponent }
        ).subtracting(Self.nonSongResources)

        XCTAssertFalse(songFileUids.isEmpty, "no song JSON found in the bundle at all")
        XCTAssertEqual(Set(manifest.map(\.uid)), songFileUids,
                       "manifest and bundled song files must describe exactly the same corpus")
    }

    func testManifestEntryFieldsMatchTheSourceSong() throws {
        let entry = try XCTUnwrap(repository.manifest.first(where: { $0.uid == "K65" }))
        XCTAssertEqual(entry.primaryTitle.text, "kabe kṛṣṇadhana pāba")
        XCTAssertEqual(entry.authorUid, "ndt")
        XCTAssertEqual(entry.languageOfOrigin, "ben")
        XCTAssertTrue(entry.audioAvailable)
        XCTAssertEqual(entry.firstLetter, "K")
        // manifest.md: "md5 equals the hash of that song's canonical JSON" — this is the pipeline's
        // recorded hash of pipeline/converted/K65.json (verified independently with `hashlib`).
        XCTAssertEqual(entry.md5, "2f7bcdfdae4408ce252f9615861ae8a5")

        // sectionKey (songs-list.md's stable A-Z index key) uses the pipeline-computed first_letter,
        // independent of whatever script `displayTitle`/`title(inScript:)` currently renders in.
        XCTAssertEqual(entry.sectionKey, "K")
    }

    func testManifestEntryForUnknownAuthorSentinel() throws {
        // A1 is the song.md worked example for the "?" unknown-author sentinel.
        let entry = try XCTUnwrap(repository.manifest.first(where: { $0.uid == "A1" }))
        XCTAssertEqual(entry.authorUid, "?")
        XCTAssertFalse(entry.audioAvailable)
    }

    // MARK: - Song-by-uid (docs/data/song.md — loaded only on the detail screen)

    func testSongByUidLoadsAndCachesTheFullSong() throws {
        let first = try XCTUnwrap(repository.song(uid: "K65"))
        XCTAssertEqual(first.verses.count, 4)
        XCTAssertEqual(first.audioFiles.count, 3)

        // Re-fetching returns the same (cached) value rather than re-decoding.
        let second = try XCTUnwrap(repository.song(uid: "K65"))
        XCTAssertEqual(first, second)
    }

    func testSongByUidReturnsNilForAnUnknownUidRatherThanCrashing() {
        XCTAssertNil(repository.song(uid: "NOT-A-REAL-SONG-UID"))
    }

    func testEveryManifestUidResolvesToARealBundledSong() {
        // manifest.md invariant: "Every ... uid resolves within the shipped dataset." Spot-check a
        // deterministic spread (every 47th entry) rather than all 703, to keep the test fast while
        // still covering every prefix/section of the corpus.
        let manifest = repository.manifest
        for entry in manifest.enumerated().filter({ $0.offset % 47 == 0 }).map(\.element) {
            XCTAssertNotNil(repository.song(uid: entry.uid), "manifest uid \(entry.uid) did not resolve to a bundled song")
        }
    }

    // MARK: - Author derivation (docs/data/author.md — derived at runtime, not a standalone dataset)

    func testAuthorDisplayNameForAShortCodeUid() throws {
        // "ndt" (Narottama Dāsa Ṭhākura) has a real author_display shipped on its songs, so the
        // derived catalog must surface that name rather than echoing the short code back.
        //
        // The expected string is read from the corpus instead of being pinned: pipeline's
        // fix_author_display.py now ships a Latn/IAST author_display on every song so authors honor
        // the script toggle, which changed what this resolves to (it used to be pinned to the Beng
        // form). What the repository owes callers is "the shipped display name", not one script.
        let song = try XCTUnwrap(repository.song(uid: "K65"))
        XCTAssertEqual(song.authorUid, "ndt", "K65 is this test's ndt fixture")

        let resolved = repository.authorDisplayName(forUid: "ndt")
        XCTAssertEqual(resolved, song.author, "derived author catalog must agree with the song's own author_display")
        XCTAssertNotEqual(resolved, "ndt", "a shipped author_display must win over the raw uid")
    }

    func testAuthorDisplayNameFallsBackToUidWhenNoDisplayNameShips() {
        // author.md's documented fallback: with no author_display, the uid *is* the name. Every
        // author in the current generation ships a display name, so this is asserted against a uid
        // that is deliberately absent from the catalog rather than against a specific song — the
        // fallback is a total function, and pinning it to "মনোহর দাস" (whose songs have since gained
        // a real author_display) was testing the corpus, not the code.
        let orphan = "NOT-A-REAL-AUTHOR-UID"
        XCTAssertFalse(repository.authors().contains(where: { $0.uid == orphan }))
        XCTAssertEqual(repository.authorDisplayName(forUid: orphan), orphan)
    }

    func testUnknownAuthorSentinelResolvesToAHumanReadableName() {
        // author.md invariant: the "?" sentinel always exists with an "unknown" display name.
        let name = repository.authorDisplayName(forUid: "?")
        XCTAssertFalse(name.isEmpty)
        XCTAssertNotEqual(name, "?")
    }

    func testDerivedAuthorsCoverEveryManifestAuthorUidWithNoDangling() {
        let authorUids = Set(repository.authors().map(\.uid))
        let manifestAuthorUids = Set(repository.manifest.map(\.authorUid))
        // author.md: "no dangling author_uids — every song's author resolves within the derived
        // catalog." (The derived catalog may also contain nothing extra, but coverage is the
        // invariant that matters for callers like SongSearcher/AuthorSongsView.)
        XCTAssertTrue(manifestAuthorUids.isSubset(of: authorUids))
    }

    func testAuthorsAreSortedByLocalizedName() {
        let names = repository.authors().map(\.name)
        let sorted = names.sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }
        XCTAssertEqual(names, sorted)
    }

    // MARK: - Song-group resolution (docs/data/collections.md — song_groups.json)

    func testSongGroupsSplitIntoBooksAndTopicsWithNoCollections() {
        // Books and topics both ship; the exact totals are the pipeline's business and are
        // regenerated from the Gīti-guccha Contents (this pair was pinned at 19/74 while the bundle
        // shipped 7/14). What collections.md actually guarantees is that both kinds are populated
        // and that no `collection`-kind grouping ships yet — CollectionsView's empty state is still
        // correct because Collections is deferred until accounts exist.
        XCTAssertFalse(repository.songGroups(kind: .book).isEmpty)
        XCTAssertFalse(repository.songGroups(kind: .topic).isEmpty)
        XCTAssertEqual(repository.songGroups(kind: .collection).count, 0)
    }

    func testBookGroupsAreOrderedAndCarryResolvableSongs() throws {
        // Structural invariants for every shipped book, rather than one hand-picked book's contents:
        // `book-sri-guru` was removed from the corpus by a later generation, so pinning to it tested
        // the data rather than the resolver.
        let books = repository.songGroups(kind: .book)
        XCTAssertFalse(books.isEmpty)

        for book in books {
            XCTAssertTrue(book.ordered, "books are ordered per collections.md — \(book.uid) was not")
            XCTAssertFalse(book.songUids.isEmpty, "\(book.uid) groups no songs")
            // Order is meaningful for an ordered group, so it must survive the round trip verbatim.
            let resolved = book.songUids.compactMap { repository.song(uid: $0)?.uid }
            XCTAssertEqual(resolved, book.songUids, "\(book.uid) lost or reordered songs on resolution")
        }
    }

    func testEveryGroupedSongUidResolvesToARealBundledSong() {
        // collections.md invariant: "Every entry in song_uids resolves to an existing Song" — checked
        // across every book + topic grouping, not just one sample group.
        let allGroups = repository.songGroups(kind: .book) + repository.songGroups(kind: .topic)
        XCTAssertFalse(allGroups.isEmpty)
        for group in allGroups {
            for uid in group.songUids {
                XCTAssertNotNil(repository.song(uid: uid), "\(group.uid) references missing song \(uid)")
            }
        }
    }

    // MARK: - Search integration (docs/screens/search.md via SongRepository.songSearcher)

    func testSearchIsDiacriticInsensitiveAgainstTheRealCorpus() {
        // Plain-ASCII query for a title that's only ever shipped with diacritics ("Eibāra Karuṇā
        // Kara", song V8) — an exact match once both sides are normalized, so this ranks first
        // regardless of anything else in the corpus (verified: this normalized title is unique).
        let results = repository.songSearcher.search("eibara karuna kara", limit: 5)
        XCTAssertEqual(results.first?.uid, "V8")
    }
}
