// Repository for the lunar-calendar overlay (docs/data/calendar.md).
//
// calendar.json ships 199 precomputed lunar-month windows (2020-01-01 .. 2036-01-01) plus
// 13 month blocks and 5 daily ārati slots, generated by pipeline/build_calendar.py.
// Song references are uids only - resolve them through manifestRepository/songRepository.
//
// Imported directly as a JSON module (NOT via `fs`), so this repository stays client-safe.
// That is a hard requirement here, not a preference: "what should I sing today?" depends on
// the *user's* current date, which a build-time repository cannot know. Components may import
// this module directly rather than through the '../services' barrel (which pulls in fs-based
// repositories that must never enter the client bundle - see Sidebar.tsx's import comment).
import raw from '../data/calendar.json'
import {
  ICalendar,
  ICalendarDailySlot,
  ICalendarMonth,
  ICalendarToday,
  ILunarWindow,
  IUpcomingFestival,
} from '../models/Calendar'
import { decodeCalendar } from './decode'

let cached: ICalendar | null = null

function calendar(): ICalendar {
  if (!cached) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    cached = decodeCalendar(raw as any)
  }
  return cached
}

/** ISO `YYYY-MM-DD` for a Date, in LOCAL time. `toISOString()` would convert to UTC first and
 * silently shift the date by a day for users west of Greenwich in the evening. */
function toIsoDate(d: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

function normalize(date?: Date | string): string {
  if (!date) return toIsoDate(new Date())
  return typeof date === 'string' ? date : toIsoDate(date)
}

/** The full decoded overlay. */
export function getCalendar(): ICalendar {
  return calendar()
}

/**
 * The lunar window containing `date`, or null when outside the precomputed range
 * (before `windowStart` / on or after `windowEnd`).
 *
 * Windows are half-open (`start <= date < end`) and contiguous, so at most one matches.
 */
export function getLunarWindow(date?: Date | string): ILunarWindow | null {
  const iso = normalize(date)
  return calendar().windows.find((w) => iso >= w.start && iso < w.end) ?? null
}

/** A month block by lunar name ('Kārtika') or Gaudiya name ('Dāmodara'), or null. */
export function getCalendarMonth(name: string): ICalendarMonth | null {
  const c = calendar()
  return (
    c.months.find((m) => m.lunarMonth === name || m.gaudiyaMonth === name) ?? null
  )
}

/** The daily ārati slots - these apply every day, independent of the lunar month. */
export function getDailySlots(): ICalendarDailySlot[] {
  return calendar().daily
}

/** Whole days between two ISO dates (UTC-anchored so DST can't produce a fractional day). */
function daysBetween(fromIso: string, toIso: string): number {
  const a = Date.parse(`${fromIso}T00:00:00Z`)
  const b = Date.parse(`${toIso}T00:00:00Z`)
  return Math.round((b - a) / 86_400_000)
}

/**
 * Festivals whose next observance falls on or after `date` (default today), soonest first.
 *
 * Returns fewer than `limit` — or nothing at all — when the pañjikā has no future dates: its
 * coverage stops in 2027 and has a gap at 2025-04..2026-02. Callers must handle an empty list
 * rather than assuming a festival is always upcoming.
 */
export function getUpcomingFestivals(
  limit = 3,
  date?: Date | string,
): IUpcomingFestival[] {
  const iso = normalize(date)
  return calendar()
    .festivals.map((festival) => {
      const next = festival.dates.find((d) => d >= iso)
      return next
        ? { festival, date: next, daysAway: daysBetween(iso, next) }
        : null
    })
    .filter((entry): entry is IUpcomingFestival => entry !== null)
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(0, limit)
}

/**
 * What to sing on a given date (defaults to today): the lunar window it falls in, that
 * month's songs and observances, and the daily ārati slots.
 *
 * Returns null only when `date` is outside the precomputed window range - callers should
 * fall back to `getDailySlots()`, which is always valid.
 *
 * Note `month.songs` may be an empty array even on success: Pauṣa has no festival songs in
 * the shipped corpus. Render an empty state, never fabricated rows (docs/data/calendar.md).
 */
export function getSongsForDate(date?: Date | string): ICalendarToday | null {
  const iso = normalize(date)
  const window = getLunarWindow(iso)
  if (!window) return null

  // An adhika (leap) month is Puruṣottama and carries its own block, not the block of the
  // lunar month whose name it repeats.
  const month = window.adhika
    ? getCalendarMonth('Puruṣottama') ?? getCalendarMonth(window.lunarMonth)
    : getCalendarMonth(window.lunarMonth)
  if (!month) return null

  return { date: iso, window, month, daily: calendar().daily }
}
