// Repository for SongGroup (Book / Topic / Collection - docs/data/collections.md).
//
// song_groups.json ships 93 groups (19 books + 74 topics; no `collection`-kind entries yet)
// generated by pipeline/build_song_groups.py from the Śrī Gauḍīya Gīti-guccha songbook's
// Contents hierarchy (see docs/data/collections.md "Data source"). Every entry's `song_uids`
// resolves to an existing song in the shipped corpus.
//
// Imported directly as a JSON module (NOT via `fs`), so this repository stays client-safe:
// Sidebar renders SongGroup('collection') data client-side and imports this module directly
// rather than through the '../services' barrel (which pulls in fs-based repositories that must
// never enter the client bundle - see Sidebar.tsx's import comment).
import raw from '../data/song_groups.json'
import { ISongGroup, SongGroupKind } from '../models/Collections'
import { decodeSongGroup } from './decode'

let cachedGroups: ISongGroup[] | null = null

function allGroups(): ISongGroup[] {
  if (!cachedGroups) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    cachedGroups = (raw as any[]).map(decodeSongGroup)
  }
  return cachedGroups
}

/** All SongGroups of one kind, decoded from the bundled song_groups.json. Returns [] for a kind
 * with no shipped data (currently `collection`) - callers must render an empty state, never
 * fabricated rows (docs/screens/browse.md). */
export function getSongGroups(kind: SongGroupKind): ISongGroup[] {
  return allGroups().filter((group) => group.kind === kind)
}

/** A single SongGroup by uid, or null when not found. */
export function getSongGroupByUid(uid: string): ISongGroup | null {
  return allGroups().find((group) => group.uid === uid) ?? null
}
